theme = "PaperMod"

baseURL = "https://yangcp25.github.io/"
languageCode = "zh-CN"
title = "yangcp"

[outputs]
home = ["HTML", "RSS", "JSON"]  # 搜索需要 index.json

[menu]
[[menu.main]]
name   = "Archives"
url    = "/archives/"
weight = 10

[[menu.main]]
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
name   = "Tag"
url    = "/tags/"
weight = 30

[[menu.main]]
name       = "About"
url        = "/about/me/"
weight     = 40

[pagination]
pagerSize = 5

[params]
mainSections = ["posts"]

ShowSearch = true                 # 启用搜索框
showNewTab = true
defaultTheme = "auto"
showTaxonomies = ["tags", "categories"]

comments = true                   # 启用评论
commentSystem = "utterances"
utterancesRepo = "yangcp25/yangcp25.github.io"
utterancesIssueTerm = "pathname"
utterancesTheme = "github-light"

ShowReadingTime = true           # 阅读时长
ShowToc = true                   # 显示 TOC
TocOpen = false                   # 默认展开 TOC
ShowBreadCrumbs = true           # 面包屑导航
ShowPostNavLinks = true          # 上一篇 / 下一篇
ShowCodeCopyButtons = true       # 代码复制按钮

[[params.socialIcons]]
name = "github"
url = "https://github.com/yangcp25"

[taxonomies]
tag = "tags"
category = "categories"
