theme = "PaperMod"
# 下面是 PaperMod 推荐的最简配置示例：
baseURL = "https://yangcp25.github.io/"
languageCode = "zh-CN"
title = "yangcp"
[menu]
  [[menu.main]]
    name = "Tag"
    url = "/tags/"
    weight = 10
  [[menu.main]]
   name   = "Archives"
   url    = "/archives/"
   weight = 20
#  [[menu.main]]
#    name = "项目"
#    url = "/projects/"
#    weight = 20
  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "/about/me/"
    weight     = 30
[pagination]
  pagerSize = 5   # 原来 paginate 的值
[params]
  # PaperMod 的个性化开关示例
  showNewTab = true
  defaultTheme = "auto"    # 可选 "light"/"dark"/"auto"
  # 是否在侧边栏显示分类
  showTaxonomies = ["tags", "categories"]
  # 启用 Utterances 评论

  # 启用 Utterances 评论
  commentSystem   = "utterances"
  utterancesRepo  = "yangcp25/yangcp25.github.io"
  # issueTerm 可选：使用 pathname（文章路径）或 title（文章标题）来匹配 Issue
  utterancesIssueTerm = "pathname"
  # 主题可选：github-light, github-dark, preferred-color-scheme...
  utterancesTheme  = "github-light"
[taxonomies]
  tag = "tags"
  category = "categories"